const { sequelize, TradeShow } = require("./models");

const tradeShows = [
  {
    name: "Consumer Electronics Show - CES",
    dates: "JAN/06 - JAN/09/2027",
    eventDate: "2027-01-06",
    lastYearData: true,
    todaysDate: "2026-04-03",
    biStageDays: 278,
    biStageWeeks: 39,
    biStageMonths: 9,
    city: "Las Vegas, NV",
    country: "United States",
    priority: "Medium",
    attendees: 142465,
    exhibitorsCount: 4500,
    exhibitorsExtracted: 2848,
    secondExhibitorsExtracted: 0,
    difference: 1652,
    variation: 37,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "",
    bSize: 0,
    comment: "",
    floorPlanUrl: "https://mapping.example.com/ces2027-floorplan",
    directoryUrl: "",
    firstExtractionAssigned: "Tammy",
    firstExtractionStatus: "Completed",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "Surf Expo",
    dates: "JAN/06 - JAN/08/2027",
    eventDate: "2027-01-06",
    lastYearData: true,
    todaysDate: "2026-04-03",
    biStageDays: 278,
    biStageWeeks: 39,
    biStageMonths: 9,
    city: "Orlando, FL",
    country: "United States",
    priority: "Medium",
    attendees: 0,
    exhibitorsCount: 0,
    exhibitorsExtracted: 713,
    secondExhibitorsExtracted: 0,
    difference: -713,
    variation: 0,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "https://surf.a2zinc.net/January2026/Public/EventMap.aspx?EventId=2051",
    bSize: 0,
    comment: "",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "Megha",
    firstExtractionStatus: "Completed",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "AIMExpo - American International Motorcycle Expo",
    dates: "Mar/03 - Mar/05/2027",
    eventDate: "2027-03-03",
    lastYearData: false,
    todaysDate: "2026-04-03",
    biStageDays: 334,
    biStageWeeks: 47,
    biStageMonths: 11,
    city: "Anaheim, CA",
    country: "United States",
    priority: "Medium",
    attendees: 0,
    exhibitorsCount: 0,
    exhibitorsExtracted: 460,
    secondExhibitorsExtracted: 0,
    difference: -460,
    variation: 0,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "https://s23.a2zinc.net/clients/MIC/AIME26/public/EventMap.aspx?shMode=E&ID=1388&sortMenu=103001",
    bSize: 0,
    comment: "Yes",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "Megha",
    firstExtractionStatus: "Completed",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "National Retail Federation - Retail's BIG Show - NRF",
    dates: "JAN/10 - JAN/12/2027",
    eventDate: "2027-01-10",
    lastYearData: true,
    todaysDate: "2026-04-03",
    biStageDays: 282,
    biStageWeeks: 40,
    biStageMonths: 9,
    city: "New York, NY",
    country: "United States",
    priority: "Medium",
    attendees: 40000,
    exhibitorsCount: 1000,
    exhibitorsExtracted: 601,
    secondExhibitorsExtracted: 0,
    difference: 399,
    variation: 40,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "https://bigshow27.mapyourshow.com/8_0/exhview/index.cfm",
    bSize: 0,
    comment: "",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "Mukul",
    firstExtractionStatus: "Completed",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "Future of Education Technology Conference - FETC",
    dates: "JAN/26 - JAN/29/2027",
    eventDate: "2027-01-26",
    lastYearData: false,
    todaysDate: "2026-04-03",
    biStageDays: 298,
    biStageWeeks: 42,
    biStageMonths: 10,
    city: "Orlando, FL",
    country: "United States",
    priority: "Medium",
    attendees: 8000,
    exhibitorsCount: 500,
    exhibitorsExtracted: 0,
    secondExhibitorsExtracted: 0,
    difference: 500,
    variation: 100,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "",
    bSize: 0,
    comment: "No Exhibitor list",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "",
    firstExtractionStatus: "Pending",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "Winter FancyFaire*",
    dates: "JAN/17 - JAN/19/2027",
    eventDate: "2027-01-17",
    lastYearData: false,
    todaysDate: "2026-04-03",
    biStageDays: 289,
    biStageWeeks: 41,
    biStageMonths: 10,
    city: "San Diego, CA",
    country: "United States",
    priority: "Medium",
    attendees: 7608,
    exhibitorsCount: 1116,
    exhibitorsExtracted: 1017,
    secondExhibitorsExtracted: 0,
    difference: 99,
    variation: 9,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "https://events.specialtyfood.com/event/winter-fancyfaire/exhibitors/RXZlbnRWaWV3XzEyMTQzMDM=",
    bSize: 0,
    comment: "",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "Soumaydip",
    firstExtractionStatus: "Completed",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "VMX - Veterinary Meeting & Expo",
    dates: "JAN/16 - JAN/20/2027",
    eventDate: "2027-01-16",
    lastYearData: true,
    todaysDate: "2026-04-03",
    biStageDays: 288,
    biStageWeeks: 41,
    biStageMonths: 10,
    city: "Orlando, FL",
    country: "United States",
    priority: "Medium",
    attendees: 30000,
    exhibitorsCount: 735,
    exhibitorsExtracted: 0,
    secondExhibitorsExtracted: 0,
    difference: 735,
    variation: 100,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "",
    bSize: 0,
    comment: "Coming Soon",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "",
    firstExtractionStatus: "Pending",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "SHOT SHOW",
    dates: "JAN/19 - JAN/20/2027",
    eventDate: "2027-01-19",
    lastYearData: true,
    todaysDate: "2026-04-03",
    biStageDays: 291,
    biStageWeeks: 41,
    biStageMonths: 10,
    city: "Las Vegas, NV",
    country: "United States",
    priority: "Medium",
    attendees: 53000,
    exhibitorsCount: 2555,
    exhibitorsExtracted: 0,
    secondExhibitorsExtracted: 0,
    difference: 2555,
    variation: 100,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "https://n2a.goexposoftware.com/events/ss26/goExpo/floorPlan/viewFloorPlan.php?ai=5",
    bSize: 0,
    comment: "",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "",
    firstExtractionStatus: "In Progress",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
  {
    name: "The NAMM Show",
    dates: "JAN/26 - JAN/30/2027",
    eventDate: "2027-01-26",
    lastYearData: false,
    todaysDate: "2026-04-03",
    biStageDays: 298,
    biStageWeeks: 42,
    biStageMonths: 10,
    city: "Anaheim, CA",
    country: "United States",
    priority: "Medium",
    attendees: 62000,
    exhibitorsCount: 1600,
    exhibitorsExtracted: 0,
    secondExhibitorsExtracted: 0,
    difference: 1600,
    variation: 100,
    booth20x20Above: 0,
    booth20x20Below: 0,
    url: "",
    bSize: 0,
    comment: "",
    floorPlanUrl: "",
    directoryUrl: "",
    firstExtractionAssigned: "Mukul",
    firstExtractionStatus: "In Progress",
    secondExtractionUrl: "",
    secondExtractionAssigned: "",
    secondExtractionStatus: "Pending",
  },
];

const seedTradeShows = async () => {
  try {
    await sequelize.authenticate();
    console.log("✅ Database connected");

    await sequelize.sync({ alter: true });
    console.log("✅ Tables synced");

    for (const data of tradeShows) {
      const [tradeShow, created] = await TradeShow.findOrCreate({
        where: { name: data.name, eventDate: data.eventDate },
        defaults: data,
      });

      if (created) {
        console.log(`✅ Inserted trade show: ${data.name}`);
      } else {
        await tradeShow.update(data);
        console.log(`⏭️ Updated existing trade show: ${data.name}`);
      }
    }

    console.log("\n🎉 Trade show seeding complete!");
  } catch (err) {
    console.error("❌ Seeding failed:", err);
    throw err;
  }
};

module.exports = { seedTradeShows, tradeShows };

if (require.main === module) {
  seedTradeShows()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}
